{
 "title": "Traefik 2.0 Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Requests (2xx, 3xx)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total{code=~\"[2-3].*\"}[5m])) by (entrypoint)"
    }
   ]
  },
  {
   "title": "Error Requests (4xx, 5xx)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total{code=~\"[4-5].*\"}[5m])) by (entrypoint)"
    }
   ]
  },
  {
   "title": "Bytes Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_bytes_total{direction=\"in\"}[5m])) by (entrypoint)"
    }
   ]
  },
  {
   "title": "Bytes Sent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_bytes_total{direction=\"out\"}[5m])) by (entrypoint)"
    }
   ]
  }
 ]
}